namespace: ecommerce

replicaCount: 1

image:
  repository: 207747152118.dkr.ecr.eu-central-1.amazonaws.com/product-service
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /actuator/health
  port: 8080

readinessProbe:
  path: /actuator/health
  port: 8080
