namespace: ecommerce

replicaCount: 3

image:
  repository: public.ecr.aws/t8s6r3p3/product-service
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /actuator/health
  port: 8080

readinessProbe:
  path: /actuator/health
  port: 8080
